### ISSUE TITLE
Confusing commit history/Lack of development branch

### ISSUE THREAD

**Issue by madelesi** [WFPB-fit/wfpb.fit#2]
Basically the issue is that the commit history is very confusing and makes it hard for contributors to help. For example we have 4 commits with the same message "trying to fix react-select on mobile". Now there are ways to fix a commit history, but we can leave it for now and create a plan for the future. I propose the following:

1 - Creation of a new branch, either a general "dev" branch or a branch for the specific issue "Fixing react-select on mobile."

2 - Work is done on the development branch, it's still bad to have 4 commits with same message, but at least we can fix that before pushing to master. Ideally the similar commits will be grouped together at the local repo before being pushed to development branch.

3 - Commits are "squashed" before being pushed(Again ideally this will be done at local when the commits all have the same purpose/message.) using either [rebase](https://blog.carbonfive.com/2017/08/28/always-squash-and-rebase-your-git-commits/) or a [simple reset & commit](https://web.archive.org/web/20180212221911/https://services.github.com/on-demand/git-trouble/too-many-commits) which is simpler in my opinion.

4 - Commits are pushed to the dev branch, and only when they are ready/passed all tests, are merged to master branch. This is important, as master should always be deployable(Never push to master unless 100% sure it is ready, mistakes happen of course.)

Of course its your repo and you can do it how you want, but at the moment it's very hard to contribute to. In short a development branch should be created and we should avoid 2 mistakes: 1 - Commits with same purpose/message (rebase/ reset&commit) 2 - Development should primarily be done on dev branch and only merged to master when it is ready & passed tests. The site is really interesting and the amount of data on it very comprehensive, so lets take care of it.

**Comment by JarLowrey** [comment]
Lol yeah I know it's bad, it's been a personal project for awhile so I haven't worried about commit messages. The code's pretty messy in certain places as well. I do have CD setup though netlify to the master branch, so I agree a dev branch would be good. I'll get working on that. I have also fixed the issue you referred to.

**Comment by madelesi** [comment]
Ok cool, we need not make big changes, just have to start creating branches for issues/features and keep master safe at all times. When someone sees 4 consecutive commits on master for the same issue it means the branch is not stable, and cloning it to start contributing is not viable.
